const items = [
    { name: 'Boots', key: '1001' },
    { name: 'Faerie Charm', key: '1004' },
    { name: 'Rejuvenation Bead', key: '1006' },
    { name: "Giant's Belt", key: '1011' },
    { name: 'Cloak of Agility', key: '1018' },
    { name: 'Blasting Wand', key: '1026' },
    { name: 'Sapphire Crystal', key: '1027' },
    { name: 'Ruby Crystal', key: '1028' },
    { name: 'Cloth Armor', key: '1029' },
    { name: 'Chain Vest', key: '1031' },
    { name: 'Null-Magic Mantle', key: '1033' },
    { name: 'Emberknife', key: '1035' },
    { name: 'Long Sword', key: '1036' },
    { name: 'Pickaxe', key: '1037' },
    { name: 'B. F. Sword', key: '1038' },
    { name: 'Hailblade', key: '1039' },
    { name: 'Obsidian Edge', key: '1040' },
    { name: 'Dagger', key: '1042' },
    { name: 'Recurve Bow', key: '1043' },
    { name: 'Amplifying Tome', key: '1052' },
    { name: 'Vampiric Scepter', key: '1053' },
    { name: "Doran's Shield", key: '1054' },
    { name: "Doran's Blade", key: '1055' },
    { name: "Doran's Ring", key: '1056' },
    { name: 'Negatron Cloak', key: '1057' },
    { name: 'Needlessly Large Rod', key: '1058' },
    { name: 'Dark Seal', key: '1082' },
    { name: 'Cull', key: '1083' },
    { name: 'Scorchclaw Pup', key: '1101' },
    { name: 'Gustwalker Hatchling', key: '1102' },
    { name: 'Mosstomper Seedling', key: '1103' },
    { name: 'Eye of the Herald', key: '1104' },
    { name: 'Penetrating Bullets', key: '1500' },
    { name: 'Fortification', key: '1501' },
    { name: 'Reinforced Armor', key: '1502' },
    { name: "Warden's Eye", key: '1503' },
    { name: 'Vanguard', key: '1504' },
    { name: 'Reinforced Armor', key: '1506' },
    { name: 'Overcharged', key: '1507' },
    { name: 'Anti-tower Socks', key: '1508' },
    { name: 'Gusto', key: '1509' },
    { name: 'Phreakish Gusto', key: '1510' },
    { name: 'Super Mech Armor', key: '1511' },
    { name: 'Super Mech Power Field', key: '1512' },
    { name: 'Turret Plating', key: '1515' },
    { name: 'Structure Bounty', key: '1516' },
    { name: 'Structure Bounty', key: '1517' },
    { name: 'Structure Bounty', key: '1518' },
    { name: 'Structure Bounty', key: '1519' },
    { name: 'OvererchargedHA', key: '1520' },
    { name: 'Fortification', key: '1521' },
    { name: 'Tower Power-Up', key: '1522' },
    { name: 'Health Potion', key: '2003' },
    { name: 'Total Biscuit of Everlasting Will', key: '2010' },
    { name: 'Kircheis Shard', key: '2015' },
    { name: 'Steel Sigil', key: '2019' },
    { name: 'Refillable Potion', key: '2031' },
    { name: 'Corrupting Potion', key: '2033' },
    { name: "Guardian's Amulet", key: '2049' },
    { name: "Guardian's Shroud", key: '2050' },
    { name: "Guardian's Horn", key: '2051' },
    { name: 'Poro-Snax', key: '2052' },
    { name: 'Control Ward', key: '2055' },
    { name: "Shurelya's Battlesong", key: '2065' },
    { name: 'Elixir of Iron', key: '2138' },
    { name: 'Elixir of Sorcery', key: '2139' },
    { name: 'Elixir of Wrath', key: '2140' },
    { name: 'Cappa Juice', key: '2141' },
    { name: 'Juice of Power', key: '2142' },
    { name: 'Juice of Vitality', key: '2143' },
    { name: 'Juice of Haste', key: '2144' },
    { name: 'Minion Dematerializer', key: '2403' },
    { name: 'Commencing Stopwatch', key: '2419' },
    { name: 'Stopwatch', key: '2420' },
    { name: 'Broken Stopwatch', key: '2421' },
    { name: 'Slightly Magical Footwear', key: '2422' },
    { name: 'Perfectly Timed Stopwatch', key: '2423' },
    { name: 'Broken Stopwatch', key: '2424' },
    { name: 'Evenshroud', key: '3001' },
    { name: "Archangel's Staff", key: '3003' },
    { name: 'Manamune', key: '3004' },
    { name: "Berserker's Greaves", key: '3006' },
    { name: 'Boots of Swiftness', key: '3009' },
    { name: 'Chemtech Putrifier', key: '3011' },
    { name: 'Chalice of Blessing', key: '3012' },
    { name: "Sorcerer's Shoes", key: '3020' },
    { name: 'Lifewell Pendant', key: '3023' },
    { name: 'Glacial Buckler', key: '3024' },
    { name: 'Guardian Angel', key: '3026' },
    { name: 'Infinity Edge', key: '3031' },
    { name: 'Mortal Reminder', key: '3033' },
    { name: 'Last Whisper', key: '3035' },
    { name: "Lord Dominik's Regards", key: '3036' },
    { name: "Seraph's Embrace", key: '3040' },
    { name: "Mejai's Soulstealer", key: '3041' },
    { name: 'Muramana', key: '3042' },
    { name: 'Phage', key: '3044' },
    { name: 'Phantom Dancer', key: '3046' },
    { name: 'Plated Steelcaps', key: '3047' },
    { name: "Zeke's Convergence", key: '3050' },
    { name: 'Hearthbound Axe', key: '3051' },
    { name: "Sterak's Gage", key: '3053' },
    { name: 'Sheen', key: '3057' },
    { name: 'Spirit Visage', key: '3065' },
    { name: 'Winged Moonplate', key: '3066' },
    { name: 'Kindlegem', key: '3067' },
    { name: 'Sunfire Aegis', key: '3068' },
    { name: 'Tear of the Goddess', key: '3070' },
    { name: 'Black Cleaver', key: '3071' },
    { name: 'Bloodthirster', key: '3072' },
    { name: 'Ravenous Hydra', key: '3074' },
    { name: 'Thornmail', key: '3075' },
    { name: 'Bramble Vest', key: '3076' },
    { name: 'Tiamat', key: '3077' },
    { name: 'Trinity Force', key: '3078' },
    { name: "Warden's Mail", key: '3082' },
    { name: "Warmog's Armor", key: '3083' },
    { name: 'Heartsteel', key: '3084' },
    { name: "Runaan's Hurricane", key: '3085' },
    { name: 'Zeal', key: '3086' },
    { name: 'Statikk Shiv', key: '3087' },
    { name: "Rabadon's Deathcap", key: '3089' },
    { name: "Wit's End", key: '3091' },
    { name: 'Rapid Firecannon', key: '3094' },
    { name: 'Stormrazor', key: '3095' },
    { name: 'Lich Bane', key: '3100' },
    { name: "Banshee's Veil", key: '3102' },
    { name: 'Aegis of the Legion', key: '3105' },
    { name: 'Redemption', key: '3107' },
    { name: 'Fiendish Codex', key: '3108' },
    { name: "Knight's Vow", key: '3109' },
    { name: 'Frozen Heart', key: '3110' },
    { name: "Mercury's Treads", key: '3111' },
    { name: "Guardian's Orb", key: '3112' },
    { name: 'Aether Wisp', key: '3113' },
    { name: 'Forbidden Idol', key: '3114' },
    { name: "Nashor's Tooth", key: '3115' },
    { name: "Rylai's Crystal Scepter", key: '3116' },
    { name: 'Mobility Boots', key: '3117' },
    { name: "Winter's Approach", key: '3119' },
    { name: 'Fimbulwinter', key: '3121' },
    { name: "Executioner's Calling", key: '3123' },
    { name: "Guinsoo's Rageblade", key: '3124' },
    { name: 'Deathfire Grasp', key: '3128' },
    { name: "Caulfield's Warhammer", key: '3133' },
    { name: 'Serrated Dirk', key: '3134' },
    { name: 'Void Staff', key: '3135' },
    { name: 'Mercurial Scimitar', key: '3139' },
    { name: 'Quicksilver Sash', key: '3140' },
    { name: "Youmuu's Ghostblade", key: '3142' },
    { name: "Randuin's Omen", key: '3143' },
    { name: 'Hextech Alternator', key: '3145' },
    { name: 'Hextech Rocketbelt', key: '3152' },
    { name: 'Blade of The Ruined King', key: '3153' },
    { name: 'Hexdrinker', key: '3155' },
    { name: 'Maw of Malmortius', key: '3156' },
    { name: "Zhonya's Hourglass", key: '3157' },
    { name: 'Ionian Boots of Lucidity', key: '3158' },
    { name: 'Spear Of Shojin', key: '3161' },
    { name: 'Morellonomicon', key: '3165' },
    { name: "Guardian's Blade", key: '3177' },
    { name: 'Umbral Glaive', key: '3179' },
    { name: 'Hullbreaker', key: '3181' },
    { name: "Guardian's Hammer", key: '3184' },
    { name: 'Locket of the Iron Solari', key: '3190' },
    { name: "Seeker's Armguard", key: '3191' },
    { name: 'Gargoyle Stoneplate', key: '3193' },
    { name: "Spectre's Cowl", key: '3211' },
    { name: "Mikael's Blessing", key: '3222' },
    { name: 'Scarecrow Effigy', key: '3330' },
    { name: 'Stealth Ward', key: '3340' },
    { name: 'Arcane Sweeper', key: '3348' },
    { name: 'Lucent Singularity', key: '3349' },
    { name: 'Farsight Alteration', key: '3363' },
    { name: 'Oracle Lens', key: '3364' },
    { name: 'Your Cut', key: '3400' },
    { name: 'Rite Of Ruin', key: '3430' },
    { name: 'Ardent Censer', key: '3504' },
    { name: 'Essence Reaver', key: '3508' },
    { name: 'Eye of the Herald', key: '3513' },
    { name: "Kalista's Black Spear", key: '3599' },
    { name: "Kalista's Black Spear", key: '3600' },
    { name: "Dead Man's Plate", key: '3742' },
    { name: 'Titanic Hydra', key: '3748' },
    { name: 'Crystalline Bracer', key: '3801' },
    { name: 'Lost Chapter', key: '3802' },
    { name: 'Catalyst of Aeons', key: '3803' },
    { name: 'Edge of Night', key: '3814' },
    { name: "Spellthief's Edge", key: '3850' },
    { name: 'Frostfang', key: '3851' },
    { name: 'Shard of True Ice', key: '3853' },
    { name: 'Steel Shoulderguards', key: '3854' },
    { name: 'Runesteel Spaulders', key: '3855' },
    { name: 'Pauldrons of Whiterock', key: '3857' },
    { name: 'Relic Shield', key: '3858' },
    { name: "Targon's Buckler", key: '3859' },
    { name: 'Bulwark of the Mountain', key: '3860' },
    { name: 'Spectral Sickle', key: '3862' },
    { name: 'Harrowing Crescent', key: '3863' },
    { name: 'Black Mist Scythe', key: '3864' },
    { name: '<rarityLegendary>Fire at Will</rarityLegendary><br…ilver>500 Silver Serpents</silver></subtitleLeft>', key: '3901' },
    { name: "<rarityLegendary>Death's Daughter</rarityLegendary…ilver>500 Silver Serpents</silver></subtitleLeft>", key: '3902' },
    { name: '<rarityLegendary>Raise Morale</rarityLegendary><br…ilver>500 Silver Serpents</silver></subtitleLeft>', key: '3903' },
    { name: 'Oblivion Orb', key: '3916' },
    { name: 'Imperial Mandate', key: '4005' },
    { name: "Bloodletter's Curse", key: '4010' },
    { name: 'Force of Nature', key: '4401' },
    { name: 'The Golden Spatula', key: '4403' },
    { name: 'Horizon Focus', key: '4628' },
    { name: 'Cosmic Drive', key: '4629' },
    { name: 'Blighting Jewel', key: '4630' },
    { name: 'Verdant Barrier', key: '4632' },
    { name: 'Riftmaker', key: '4633' },
    { name: 'Leeching Leer', key: '4635' },
    { name: 'Night Harvester', key: '4636' },
    { name: 'Demonic Embrace', key: '4637' },
    { name: 'Watchful Wardstone', key: '4638' },
    { name: 'Stirring Wardstone', key: '4641' },
    { name: 'Bandleglass Mirror', key: '4642' },
    { name: 'Vigilant Wardstone', key: '4643' },
    { name: 'Crown of the Shattered Queen', key: '4644' },
    { name: 'Shadowflame', key: '4645' },
    { name: 'Ironspike Whip', key: '6029' },
    { name: 'Silvermere Dawn', key: '6035' },
    { name: "Death's Dance", key: '6333' },
    { name: 'Chempunk Chainsword', key: '6609' },
    { name: 'Staff of Flowing Water', key: '6616' },
    { name: 'Moonstone Renewer', key: '6617' },
    { name: 'Echoes of Helia', key: '6620' },
    { name: 'Goredrinker', key: '6630' },
    { name: 'Stridebreaker', key: '6631' },
    { name: 'Divine Sunderer', key: '6632' },
    { name: "Liandry's Anguish", key: '6653' },
    { name: "Luden's Tempest", key: '6655' },
    { name: 'Everfrost', key: '6656' },
    { name: 'Rod of Ages', key: '6657' },
    { name: "Bami's Cinder", key: '6660' },
    { name: 'Iceborn Gauntlet', key: '6662' },
    { name: 'Turbo Chemtank', key: '6664' },
    { name: "Jak'Sho, The Protean", key: '6665' },
    { name: 'Radiant Virtue', key: '6667' },
    { name: 'Noonquiver', key: '6670' },
    { name: 'Galeforce', key: '6671' },
    { name: 'Kraken Slayer', key: '6672' },
    { name: 'Immortal Shieldbow', key: '6673' },
    { name: 'Navori Quickblades', key: '6675' },
    { name: 'The Collector', key: '6676' },
    { name: 'Rageknife', key: '6677' },
    { name: 'Duskblade of Draktharr', key: '6691' },
    { name: 'Eclipse', key: '6692' },
    { name: "Prowler's Claw", key: '6693' },
    { name: "Serylda's Grudge", key: '6694' },
    { name: "Serpent's Fang", key: '6695' },
    { name: 'Axiom Arc', key: '6696' },
    { name: "Sandshrike's Claw", key: '7000' },
    { name: 'Syzygy', key: '7001' },
    { name: "Draktharr's Shadowcarver", key: '7002' },
    { name: 'Frozen Fist', key: '7005' },
    { name: 'Typhoon', key: '7006' },
    { name: "Icathia's Curse", key: '7009' },
    { name: 'Vespertide', key: '7010' },
    { name: 'Upgraded Aeropack', key: '7011' },
    { name: "Liandry's Lament", key: '7012' },
    { name: 'Eye of Luden', key: '7013' },
    { name: 'Eternal Winter', key: '7014' },
    { name: 'Ceaseless Hunger', key: '7015' },
    { name: 'Dreamshatter', key: '7016' },
    { name: 'Deicide', key: '7017' },
    { name: 'Infinity Force', key: '7018' },
    { name: 'Reliquary of the Golden Dawn', key: '7019' },
    { name: "Shurelya's Requiem", key: '7020' },
    { name: 'Starcaster', key: '7021' },
    { name: 'Equinox', key: '7023' },
    { name: 'Caesura', key: '7024' },
    { name: 'Leviathan', key: '7025' },
    { name: 'The Unspoken Parasite', key: '7026' },
    { name: 'Primordial Dawn', key: '7027' },
    { name: 'Infinite Convergence', key: '7028' },
    { name: "Youmuu's Wake", key: '7029' },
    { name: 'Seething Sorrow', key: '7030' },
    { name: 'Edge of Finality', key: '7031' },
    { name: 'Flicker', key: '7032' },
    { name: 'Cry of the Shrieking City', key: '7033' },
    { name: 'Gangplank Placeholder', key: '7050' },
    { name: "Anathema's Chains", key: '8001' },
    { name: 'Abyssal Mask', key: '8020' },
    { name: "Guardian's Horn", key: '222051' },
    { name: "Shurelya's Battlesong", key: '222065' },
    { name: 'Evenshroud', key: '223001' },
    { name: "Archangel's Staff", key: '223003' },
    { name: 'Manamune', key: '223004' },
    { name: 'Ghostcrawlers', key: '223005' },
    { name: "Berserker's Greaves", key: '223006' },
    { name: 'Boots of Swiftness', key: '223009' },
    { name: 'Chemtech Putrifier', key: '223011' },
    { name: "Sorcerer's Shoes", key: '223020' },
    { name: 'Guardian Angel', key: '223026' },
    { name: 'Infinity Edge', key: '223031' },
    { name: 'Mortal Reminder', key: '223033' },
    { name: "Lord Dominik's Regards", key: '223036' },
    { name: "Atma's Reckoning", key: '223039' },
    { name: "Seraph's Embrace", key: '223040' },
    { name: 'Muramana', key: '223042' },
    { name: 'Phantom Dancer', key: '223046' },
    { name: 'Plated Steelcaps', key: '223047' },
    { name: "Zeke's Convergence", key: '223050' },
    { name: "Sterak's Gage", key: '223053' },
    { name: 'Spirit Visage', key: '223065' },
    { name: 'Sunfire Aegis', key: '223068' },
    { name: 'Black Cleaver', key: '223071' },
    { name: 'Bloodthirster', key: '223072' },
    { name: 'Ravenous Hydra', key: '223074' },
    { name: 'Thornmail', key: '223075' },
    { name: 'Trinity Force', key: '223078' },
    { name: 'Heartsteel', key: '223084' },
    { name: "Runaan's Hurricane", key: '223085' },
    { name: 'Statikk Shiv', key: '223087' },
    { name: "Rabadon's Deathcap", key: '223089' },
    { name: "Wit's End", key: '223091' },
    { name: 'Rapid Firecannon', key: '223094' },
    { name: 'Stormrazor', key: '223095' },
    { name: 'Lich Bane', key: '223100' },
    { name: "Banshee's Veil", key: '223102' },
    { name: 'Redemption', key: '223107' },
    { name: "Knight's Vow", key: '223109' },
    { name: 'Frozen Heart', key: '223110' },
    { name: "Mercury's Treads", key: '223111' },
    { name: "Guardian's Orb", key: '223112' },
    { name: "Nashor's Tooth", key: '223115' },
    { name: "Rylai's Crystal Scepter", key: '223116' },
    { name: "Winter's Approach", key: '223119' },
    { name: 'Fimbulwinter', key: '223121' },
    { name: "Guinsoo's Rageblade", key: '223124' },
    { name: 'Void Staff', key: '223135' },
    { name: 'Mercurial Scimitar', key: '223139' },
    { name: "Youmuu's Ghostblade", key: '223142' },
    { name: "Randuin's Omen", key: '223143' },
    { name: 'Hextech Gunblade', key: '223146' },
    { name: 'Hextech Rocketbelt', key: '223152' },
    { name: 'Blade of The Ruined King', key: '223153' },
    { name: 'Maw of Malmortius', key: '223156' },
    { name: "Zhonya's Hourglass", key: '223157' },
    { name: 'Ionian Boots of Lucidity', key: '223158' },
    { name: 'Spear Of Shojin', key: '223161' },
    { name: 'Morellonomicon', key: '223165' },
    { name: 'Zephyr', key: '223172' },
    { name: "Guardian's Blade", key: '223177' },
    { name: 'Hullbreaker', key: '223181' },
    { name: "Guardian's Hammer", key: '223184' },
    { name: "Guardian's Dirk", key: '223185' },
    { name: 'Locket of the Iron Solari', key: '223190' },
    { name: 'Gargoyle Stoneplate', key: '223193' },
    { name: "Mikael's Blessing", key: '223222' },
    { name: 'Ardent Censer', key: '223504' },
    { name: 'Essence Reaver', key: '223508' },
    { name: "Dead Man's Plate", key: '223742' },
    { name: 'Titanic Hydra', key: '223748' },
    { name: 'Edge of Night', key: '223814' },
    { name: 'Spectral Cutlass', key: '224004' },
    { name: 'Imperial Mandate', key: '224005' },
    { name: 'Force of Nature', key: '224401' },
    { name: 'The Golden Spatula', key: '224403' },
    { name: 'Horizon Focus', key: '224628' },
    { name: 'Cosmic Drive', key: '224629' },
    { name: 'Riftmaker', key: '224633' },
    { name: 'Night Harvester', key: '224636' },
    { name: 'Demonic Embrace', key: '224637' },
    { name: 'Crown of the Shattered Queen', key: '224644' },
    { name: 'Shadowflame', key: '224645' },
    { name: 'Silvermere Dawn', key: '226035' },
    { name: "Death's Dance", key: '226333' },
    { name: 'Chempunk Chainsword', key: '226609' },
    { name: 'Staff of Flowing Water', key: '226616' },
    { name: 'Moonstone Renewer', key: '226617' },
    { name: 'Echoes of Helia', key: '226620' },
    { name: 'Goredrinker', key: '226630' },
    { name: 'Stridebreaker', key: '226631' },
    { name: 'Divine Sunderer', key: '226632' },
    { name: "Liandry's Anguish", key: '226653' },
    { name: "Luden's Tempest", key: '226655' },
    { name: 'Everfrost', key: '226656' },
    { name: 'Rod of Ages', key: '226657' },
    { name: "Bami's Cinder", key: '226660' },
    { name: 'Iceborn Gauntlet', key: '226662' },
    { name: 'Turbo Chemtank', key: '226664' },
    { name: "Jak'Sho, The Protean", key: '226665' },
    { name: 'Radiant Virtue', key: '226667' },
    { name: 'Galeforce', key: '226671' },
    { name: 'Kraken Slayer', key: '226672' },
    { name: 'Immortal Shieldbow', key: '226673' },
    { name: 'Navori Quickblades', key: '226675' },
    { name: 'The Collector', key: '226676' },
    { name: 'Duskblade of Draktharr', key: '226691' },
    { name: 'Eclipse', key: '226692' },
    { name: "Prowler's Claw", key: '226693' },
    { name: "Serylda's Grudge", key: '226694' },
    { name: "Serpent's Fang", key: '226695' },
    { name: 'Axiom Arc', key: '226696' },
    { name: 'Syzygy', key: '227001' },
    { name: "Draktharr's Shadowcarver", key: '227002' },
    { name: 'Frozen Fist', key: '227005' },
    { name: 'Typhoon', key: '227006' },
    { name: "Icathia's Curse", key: '227009' },
    { name: 'Vespertide', key: '227010' },
    { name: 'Upgraded Aeropack', key: '227011' },
    { name: "Liandry's Lament", key: '227012' },
    { name: 'Eye of Luden', key: '227013' },
    { name: 'Eternal Winter', key: '227014' },
    { name: 'Ceaseless Hunger', key: '227015' },
    { name: 'Dreamshatter', key: '227016' },
    { name: 'Deicide', key: '227017' },
    { name: 'Infinity Force', key: '227018' },
    { name: 'Reliquary of the Golden Dawn', key: '227019' },
    { name: "Shurelya's Requiem", key: '227020' },
    { name: 'Starcaster', key: '227021' },
    { name: 'Equinox', key: '227023' },
    { name: 'Caesura', key: '227024' },
    { name: 'Leviathan', key: '227025' },
    { name: 'The Unspoken Parasite', key: '227026' },
    { name: 'Primordial Dawn', key: '227027' },
    { name: 'Infinite Convergence', key: '227028' },
    { name: "Youmuu's Wake", key: '227029' },
    { name: 'Seething Sorrow', key: '227030' },
    { name: 'Edge of Finality', key: '227031' },
    { name: 'Flicker', key: '227032' },
    { name: 'Cry of the Shrieking City', key: '227033' },
    { name: "Anathema's Chains", key: '228001' },
    { name: 'Abyssal Mask', key: '228020' },
];