const itemNames: string[] = [
    "Boots",
    "Faerie Charm",
    "Rejuvenation Bead",
    "Giant's Belt",
    "Cloak of Agility",
    "Blasting Wand",
    "Sapphire Crystal",
    "Ruby Crystal",
    "Cloth Armor",
    "Chain Vest",
    "Null-Magic Mantle",
    "Emberknife",
    "Long Sword",
    "Pickaxe",
    "B. F. Sword",
    "Hailblade",
    "Obsidian Edge",
    "Dagger",
    "Recurve Bow",
    "Amplifying Tome",
    "Vampiric Scepter",
    "Doran's Shield",
    "Doran's Blade",
    "Doran's Ring",
    "Negatron Cloak",
    "Needlessly Large Rod",
    "Dark Seal",
    "Cull",
    "Scorchclaw Pup",
    "Gustwalker Hatchling",
    "Mosstomper Seedling",
    "Eye of the Herald",
    "Penetrating Bullets",
    "Fortification",
    "Reinforced Armor",
    "Warden's Eye",
    "Vanguard",
    "Reinforced Armor",
    "Overcharged",
    "Anti-tower Socks",
    "Gusto",
    "Phreakish Gusto",
    "Super Mech Armor",
    "Super Mech Power Field",
    "Turret Plating",
    "Structure Bounty",
    "Structure Bounty",
    "Structure Bounty",
    "Structure Bounty",
    "OvererchargedHA",
    "Fortification",
    "Tower Power-Up",
    "Health Potion",
    "Total Biscuit of Everlasting Will",
    "Kircheis Shard",
    "Steel Sigil",
    "Refillable Potion",
    "Corrupting Potion",
    "Guardian's Amulet",
    "Guardian's Shroud",
    "Guardian's Horn",
    "Poro-Snax",
    "Control Ward",
    "Shurelya's Battlesong",
    "Elixir of Iron",
    "Elixir of Sorcery",
    "Elixir of Wrath",
    "Cappa Juice",
    "Juice of Power",
    "Juice of Vitality",
    "Juice of Haste",
    "Minion Dematerializer",
    "Commencing Stopwatch",
    "Stopwatch",
    "Broken Stopwatch",
    "Slightly Magical Footwear",
    "Perfectly Timed Stopwatch",
    "Broken Stopwatch",
    "Evenshroud",
    "Archangel's Staff",
    "Manamune",
    "Ghostcrawlers",
    "Berserker's Greaves",
    "Boots of Swiftness",
    "Chemtech Putrifier",
    "Chalice of Blessing",
    "Sorcerer's Shoes",
    "Lifewell Pendant",
    "Glacial Buckler",
    "Guardian Angel",
    "Infinity Edge",
    "Mortal Reminder",
    "Last Whisper",
    "Lord Dominik's Regards",
    "Atma's Reckoning",
    "Seraph's Embrace",
    "Mejai's Soulstealer",
    "Muramana",
    "Phage",
    "Phantom Dancer",
    "Plated Steelcaps",
    "Zeke's Convergence",
    "Hearthbound Axe",
    "Sterak's Gage",
    "Sheen",
    "Spirit Visage",
    "Winged Moonplate",
    "Kindlegem",
    "Sunfire Aegis",
    "Tear of the Goddess",
    "Black Cleaver",
    "Bloodthirster",
    "Ravenous Hydra",
    "Thornmail",
    "Bramble Vest",
    "Tiamat",
    "Trinity Force",
    "Warden's Mail",
    "Warmog's Armor",
    "Heartsteel",
    "Runaan's Hurricane",
    "Zeal",
    "Statikk Shiv",
    "Rabadon's Deathcap",
    "Wit's End",
    "Rapid Firecannon",
    "Stormrazor",
    "Lich Bane",
    "Banshee's Veil",
    "Aegis of the Legion",
    "Redemption",
    "Fiendish Codex",
    "Knight's Vow",
    "Frozen Heart",
    "Mercury's Treads",
    "Guardian's Orb",
    "Aether Wisp",
    "Forbidden Idol",
    "Nashor's Tooth",
    "Rylai's Crystal Scepter",
    "Mobility Boots",
    "Winter's Approach",
    "Fimbulwinter",
    "Executioner's Calling",
    "Guinsoo's Rageblade",
    "Deathfire Grasp",
    "Sword of the Divine",
    "Caulfield's Warhammer",
    "Serrated Dirk",
    "Void Staff",
    "Mercurial Scimitar",
    "Quicksilver Sash",
    "Youmuu's Ghostblade",
    "Randuin's Omen",
    "Hextech Alternator",
    "Hextech Gunblade",
    "Hextech Rocketbelt",
    "Blade of The Ruined King",
    "Hexdrinker",
    "Maw of Malmortius",
    "Zhonya's Hourglass",
    "Ionian Boots of Lucidity",
    "Spear of Shojin",
    "Morellonomicon",
    "Zephyr",
    "Guardian's Blade",
    "Umbral Glaive",
    "Hullbreaker",
    "Guardian's Hammer",
    "Locket of the Iron Solari",
    "Seeker's Armguard",
    "Gargoyle Stoneplate",
    "Spectre's Cowl",
    "Mikael's Blessing",
    "Scarecrow Effigy",
    "Stealth Ward",
    "Arcane Sweeper",
    "Lucent Singularity",
    "Farsight Alteration",
    "Oracle Lens",
    "Your Cut",
    "Rite Of Ruin",
    "Ardent Censer",
    "Essence Reaver",
    "Eye of the Herald",
    "Kalista's Black Spear",
    "Kalista's Black Spear",
    "Dead Man's Plate",
    "Titanic Hydra",
    "Crystalline Bracer",
    "Lost Chapter",
    "Catalyst of Aeons",
    "Edge of Night",
    "Spellthief's Edge",
    "Frostfang",
    "Shard of True Ice",
    "Steel Shoulderguards",
    "Runesteel Spaulders",
    "Pauldrons of Whiterock",
    "Relic Shield"
];

console.log(itemNames);
